export const DISCORD_CLIENT_ID = process.env.DISCORD_CLIENT_ID || ''
export const DISCORD_CLIENT_SECRET = process.env.DISCORD_CLIENT_SECRET || ''
export const DISCORD_GUILD_ID = process.env.DISCORD_GUILD_ID || ''
export const MONGO_URI = process.env.MONGO_URI || ''
export const DISCORD_TOKEN = process.env.DISCORD_TOKEN || ''
