export { Agenda } from './agenda.page'
export { Login } from './login.page'
export { Event } from './event.page'
export { Skills } from './skills.page'
export { Repertoire } from './repertoire.page'
export { Games } from './games.page'
